version: 0.2

phases:
  install:
    commands:
      - echo "Installing Helm..."
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - helm version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Setting up Kubeconfig for Helm..."
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG ./app
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Docker image build and push complete!"

      - echo "Updating Helm chart with new image tag..."
      # Navigate to the Helm chart folder
      - cd $CODEBUILD_SRC_DIR/my-flask-chart
      # Replace tag in values.yaml
      - 'sed -i "s|tag: latest|tag: $IMAGE_TAG|" values.yaml'
      # Package Helm chart into /tmp
      - helm package . --destination /tmp
      - echo "Helm chart packaged successfully"

  post_build:
    commands:
      - echo "Build completed successfully. Artifacts prepared."

artifacts:
  files:
    - /tmp/*.tgz
  discard-paths: yes
