version: 0.2

phases:
  install:
    commands:
      - echo "Installing Helm..."
      - apt-get update -y
      - apt-get install -y curl tar gzip bash
      - curl -fsSL https://get.helm.sh/helm-v3.19.0-linux-amd64.tar.gz -o helm.tar.gz
      - tar -zxvf helm.tar.gz
      - mv linux-amd64/helm /usr/local/bin/helm
      - helm version
      - kubectl version --client

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - echo "Logging in to Docker Hub to avoid rate limit..."
      - echo $"DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME"--password-stdin
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Setting up Kubeconfig for Helm..."
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG ./app
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Docker image build and push complete!"

      - echo "Packaging Helm Chart..."
      - cd my-flask-chart
      - 'sed -i "s|tag: latest|tag: $IMAGE_TAG|" values.yaml'
      - helm package .
      - mv *.tgz /tmp/my-flask-app.tgz

  post_build:
    commands:
      - echo "Build completed successfully. Artifacts prepared."

artifacts:
  files:
    - '/tmp/my-flask-app.tgz'
  discard-paths: yes


